// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sievert.Data;

#nullable disable

namespace Sievert.Data.Migrations
{
    [DbContext(typeof(SievertContext))]
    [Migration("20260913182556_DemoVeriIsareti")]
    partial class DemoVeriIsareti
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sievert.Data.Entities.AnalysisJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveDeduplicationKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("HeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsResultComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("integer");

                    b.Property<double?>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("SourceCommitChangedDuringAnalysis")
                        .HasColumnType("boolean");

                    b.Property<int?>("SourceDirtyFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceHeadSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SourceHeadShortSha")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SourceRepositoryIdentity")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("SourceStateCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SourceStateVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceTreeState")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TotalItems")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WorkerInstanceId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDeduplicationKey")
                        .IsUnique();

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("RepositoryId", "RequestedAtUtc");

                    b.ToTable("AnalysisJobs");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitFileRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCSharp")
                        .HasColumnType("boolean");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<string>("OldPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("Path");

                    b.ToTable("CommitFiles");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitMetricRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorCommitCount")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorFileExperience")
                        .HasColumnType("integer");

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.Property<int>("CsFilesChanged")
                        .HasColumnType("integer");

                    b.Property<int>("DirectoryCount")
                        .HasColumnType("integer");

                    b.Property<int>("DistinctAuthorsOnFiles")
                        .HasColumnType("integer");

                    b.Property<double>("Entropy")
                        .HasColumnType("double precision");

                    b.Property<int>("FilesChanged")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFix")
                        .HasColumnType("boolean");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("MaxFileAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("MinFileAgeDays")
                        .HasColumnType("integer");

                    b.Property<int>("PriorChanges")
                        .HasColumnType("integer");

                    b.Property<int>("PriorFixes")
                        .HasColumnType("integer");

                    b.Property<int>("SubsystemCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommitId")
                        .IsUnique();

                    b.ToTable("CommitMetrics");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRiskSnapshotRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DecisionAt05")
                        .HasColumnType("boolean");

                    b.Property<bool>("DecisionAtTrainThreshold")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCalibrated")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ModelProfile")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double>("RawModelScore")
                        .HasColumnType("double precision");

                    b.Property<double>("RiskIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("TrainThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("WarningCodes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("AnalysisJobId", "CommitId")
                        .IsUnique();

                    b.HasIndex("AnalysisJobId", "RawModelScore");

                    b.ToTable("CommitRiskSnapshots");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AuthorDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("ChangedCSharpFiles")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("CoAuthorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBugIntroducing")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<string>("MessageFull")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageSubject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDateUtc");

                    b.HasIndex("IsBugIntroducing");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Sievert.Data.Entities.ReportArtifactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("boolean");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManifestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RiskAnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("StaticAnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisJobId")
                        .IsUnique();

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "IdempotencyKey");

                    b.HasIndex("RepositoryId", "RequestedAtUtc");

                    b.ToTable("ReportArtifacts");
                });

            modelBuilder.Entity("Sievert.Data.Entities.RepositoryRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FirstCommitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("IdentitySource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDemoData")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCommitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannedSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Identity")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Sievert.Data.Entities.StaticAnalysisFindingRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Column")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestCode")
                        .HasColumnType("boolean");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("MemberName")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisJobId", "RuleCode");

                    b.ToTable("StaticAnalysisFindings");
                });

            modelBuilder.Entity("Sievert.Data.Entities.AnalysisJobRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.RepositoryRow", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitFileRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.CommitRow", "Commit")
                        .WithMany("Files")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitMetricRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.CommitRow", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRiskSnapshotRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.AnalysisJobRow", "AnalysisJob")
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sievert.Data.Entities.CommitRow", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.RepositoryRow", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Sievert.Data.Entities.ReportArtifactRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.AnalysisJobRow", "AnalysisJob")
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sievert.Data.Entities.RepositoryRow", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Sievert.Data.Entities.StaticAnalysisFindingRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.AnalysisJobRow", "AnalysisJob")
                        .WithMany()
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Sievert.Data.Entities.RepositoryRow", b =>
                {
                    b.Navigation("Commits");
                });
#pragma warning restore 612, 618
        }
    }
}
