// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sievert.Data;

#nullable disable

namespace Sievert.Data.Migrations
{
    [DbContext(typeof(SievertContext))]
    [Migration("20260911171109_IlkSema")]
    partial class IlkSema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sievert.Data.Entities.CommitFileRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCSharp")
                        .HasColumnType("boolean");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<string>("OldPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CommitId");

                    b.HasIndex("Path");

                    b.ToTable("CommitFiles");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitMetricRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommitId")
                        .IsUnique();

                    b.ToTable("CommitMetrics");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AuthorDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("ChangedCSharpFiles")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("CoAuthorCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<string>("MessageFull")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageSubject")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ParentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorDateUtc");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Sievert.Data.Entities.RepositoryRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FirstCommitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCommitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("RemoteUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannedSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitFileRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.CommitRow", "Commit")
                        .WithMany("Files")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitMetricRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.CommitRow", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.HasOne("Sievert.Data.Entities.RepositoryRow", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Sievert.Data.Entities.CommitRow", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Sievert.Data.Entities.RepositoryRow", b =>
                {
                    b.Navigation("Commits");
                });
#pragma warning restore 612, 618
        }
    }
}
